var debugConsole = document.getElementById('debugConsole').textContent;

const error = document.createElement('p'),
  errorStack = document.createElement('p'),

  titleScreen = document.getElementById('titleScreen'),
  sourceNote = document.getElementById('sourceNote'),
  buildString = document.getElementById('buildString'),
  githubLink = document.getElementById('githubLink'),
  skipIntroString = document.getElementById('skipIntroString'),
  updateString = document.getElementById('updateString'),
  betaString = document.getElementById('betaString'),
  startButton = document.getElementById('startButton'),
  smallCoin1 = document.getElementById('smallCoin1'),
  smallCoin2 = document.getElementById('smallCoin2'),
  smallCoin3 = document.getElementById('smallCoin3'),
  smallCoin4 = document.getElementById('smallCoin4'),
  titleScreenClicker = document.getElementById('titleScreenClicker'),
  title = document.getElementById('title'),

  gamePanel = document.getElementById('gameScreen'),
  coin = document.getElementById('coin'),
  clickString = document.getElementById('clickString'),
  cpsString = document.getElementById('cpsString'),
  clickValueString = document.getElementById('clickValueString'),
  unlockString = document.getElementById('unlockString'),
  saveButton = document.getElementById('saveButton'),
  savingString = document.getElementById('savingString'),
  saveInfoString = document.getElementById('saveInfo'),
  buffStr = document.getElementById('buffLabel'),
  fpsLabel = document.getElementById('fpsLabel'),

  shopPanel = document.getElementById('shoppanel'),
  autoBuyStr = document.getElementById('autobuystring'),
  clickerBuy = document.getElementById('clickerbuy'),
  clickerCPSString = document.getElementById('clickercpsstring'),
  clickerCostString = document.getElementById('clickercoststring'),
  clickerInfo = document.getElementById('clickerinfo'),
  clickersOwnedString = document.getElementById('clickersownedstring'),
  clickerImage = document.getElementById('clickerimg'),
  superClickerGroup = document.getElementById('superclicker'),
  superClickerBuy = document.getElementById('superclickerbuy'),
  superClickerCPSString = document.getElementById('superclickercpsstring'),
  superClickerCostString = document.getElementById('superclickercoststring'),
  superClickersOwnedString = document.getElementById('superclickersownedstring'),
  superClickerInfo = document.getElementById('superclickerinfo'),
  superClickerImg = document.getElementById('superclickerimg'),
  doublePointerGroup = document.getElementById('doublepointer'),
  doublePointerBuy = document.getElementById('doublepointerbuy'),
  doublePointerCPSString = document.getElementById('doublepointercpsstring'),
  doublePointerCostString = document.getElementById('doublepointercoststring'),
  doublePointersOwnedString = document.getElementById('doublepointersownedstring'),
  doublePointerInfo = document.getElementById('doublepointerinfo'),
  doublePointerImage = document.getElementById('doublepointerimg'),

  // Upgrade Shop

  upgradeShopPanel = document.getElementById('upgradeshoppanel'),
  upgradeButton = document.getElementById('upgradebutton'),
  upgradeShopReturn = document.getElementById('shopreturnbutton'),

  cursorBuy = document.getElementById('cursorbuy'),
  cursorCostString = document.getElementById('cursorcoststring'),
  cursorOwnedString = document.getElementById('cursorownedstring'),
  cursorImage = document.getElementById('cursorimg'),

  superCursorGroup = document.getElementById('supercursor'),
  superCursorBuy = document.getElementById('supercursorbuy'),
  superCursorCostString = document.getElementById('supercursorcoststring'),
  superCursorOwnedString = document.getElementById('supercursorownedstring'),
  superCursorImage = document.getElementById('supercursorimg'),

  employeeGroup = document.getElementById('employee'),
  employeeBuy = document.getElementById('employeebuy'),
  employeeCostString = document.getElementById('employeecoststring'),
  employeesOwnedString = document.getElementById('employeesownedstring'),
  employeeImage = document.getElementById('employeeimg'),

  godFingerGroup = document.getElementById('godfinger'),
  godFingerBuy = document.getElementById('godfingerbuy'),
  godFingerCostString = document.getElementById('godfingercoststring'),
  godFingerOwnedString = document.getElementById('godfingerownedstring'),
  godFingerImage = document.getElementById('godfingerimg'),

  clickerFusionGroup = document.getElementById('clickerfusion'),
  clickerFusionBuy = document.getElementById('clickerfusionbuy'),
  clickerFusionCostString = document.getElementById('clickerfusioncoststring'),
  clickerFusionOwnedString = document.getElementById('clickerfusionownedstring'),
  clickerFusionInfo = document.getElementById('clickerfusioninfo'),
  clickerFusionImage = document.getElementById('clickerfusionimg'),

  // Stats Screen

  statsPanel = document.getElementById('statspanel'),
  timePlayedString = document.getElementById('timestring'),
  lifetimeClicksString = document.getElementById('lifetimeclicksstring'),
  lifetimeManualClicksString = document.getElementById('lifetimemanualclicksstring'),
  coinClickCountString = document.getElementById('coinclickcountstring'),
  totalClickHelpersString = document.getElementById('totalclickhelpersstring'),
  achievementsUnlockedString = document.getElementById('achievementsunlockedstring'),
  rawCPSString = document.getElementById('rawcpsstring'),
  rawCVString = document.getElementById('rawcvstring'),
  offlineCPSString = document.getElementById('offlinecpsstring'),

  // Debug Screen

  debugScreen = document.getElementById('debugscreen'),
  cmdForm = document.getElementById('debugconsinput'),
  commandInput = document.getElementById('debugcmdinput'),

  // Achievements

  achievementsButton = document.getElementById('achievementsbutton'),
  achievementsButtonIcon = document.getElementById('achievementsbtnicon'),
  achievementsLabel = document.getElementById('achievementslabel'),
  achievementsPanel = document.getElementById('achievementsscreen'),
  achNameStr = document.getElementById('achievementnamestring'),
  achDescStr = document.getElementById('achievementdescriptionstring'),
  achUnlockStr = document.getElementById('achievementunlockedstring'),
  journeyBegins = document.getElementById('journeybegins'),
  aGoodStart = document.getElementById('agoodstart'),
  gettingThere = document.getElementById('gettingthere'),
  millionare = document.getElementById('millionare'),
  coinPool = document.getElementById('coinpool'),
  abundance = document.getElementById('abundance'),
  billionare = document.getElementById('billionare'),
  excess = document.getElementById('excess'),
  planetOfClicks = document.getElementById('planetofclicks'),
  trillionare = document.getElementById('trillionare'),
  pocketDimension = document.getElementById('pocketdimension'),
  farTooMany = document.getElementById('fartoomany'),
  quadrillionare = document.getElementById('quadrillionare'),
  coinVortex = document.getElementById('coinvortex'),
  coinShapedBlackHole = document.getElementById('coinshapedblackhole'),
  quintillionare = document.getElementById('quintillionare'),
  clickBeyond = document.getElementById('clickbeyond'),
  distantBeginning = document.getElementById('distantbeginning'),
  sextillionare = document.getElementById('sextillionare'),
  numberOverflow = document.getElementById('numberoverflow'),
  coinUniverse = document.getElementById('coinuniverse'),
  septillionare = document.getElementById('septillionare'),
  why = document.getElementById('why'),
  twentyFingers = document.getElementById('twentyfingers'),
  forTheWorthy = document.getElementById('fortheworthy'),
  breakpoint = document.getElementById('breakpoint'),
  cheater = document.getElementById('cheater'),
  backToGame = document.getElementById('backtogame'),
  ftwIcon = document.getElementById('fortheworthyicon'),
  bpIcon = document.getElementById('breakpointicon'),
  cheaterIcon = document.getElementById('cheatericon'),

  // Settings

  settingsButton = document.getElementById('settingsbutton'),
  settingsLabel = document.getElementById('settingslabel'),
  settingsPanel = document.getElementById('settingsscreen'),
  volumeInput = document.getElementById('volumeinput'),
  autoBuyBtn = document.getElementById('autobuysetting'),
  bgGradCenterInput = document.getElementById('bggrad1input'),
  bgGradEdgeInput = document.getElementById('bggrad2input'),
  graphicsBtn = document.getElementById('graphicssetting'),
  graphicsSettingInfo = document.getElementById('graphicssettinginfo'),
  resetBgButton = document.getElementById('resetbgbutton'),
  wipeSaveButton = document.getElementById('wipesavebutton'),
  backToGame2 = document.getElementById('backtogame2');

  // Sound effects
var sfxClick = document.getElementById('sfx'),
  sfxShopBuy = document.getElementById('sfx5'),
  sfxCoinWhoosh = document.getElementById('sfx6'),
  sfxShopUnlock = document.getElementById('sfx2'),
  sfxAchievementUnlock = document.getElementById('sfx3'),
  sfxSpecialAchievementUnlock = document.getElementById('sfx4'),
  sfxTitleWhoosh = document.getElementById('sfx7'),
  sfxTitleWhoosh2 = document.getElementById('sfx7.1');
